#!/usr/bin/env bash
set -o pipefail
set -eux

BURL_ROOT="$(dirname `realpath $0`)"

. ${BURL_ROOT}/common.sh

for f in "$@"; do
    if [[ -d $f ]]; then
        for ff in $f/test-*.sh; do
            . ${ff}
            echo "--- ${ff} OK"
            BURL_STOP
        done
    elif [[ -f $f ]]; then
        . $f
        BURL_STOP
        echo "--- $f OK"
    else
        if [[ $1 == "init" ]]; then
            cp -a ${BURL_ROOT}/test-example.sh ${2:-test-example.sh}
            exit
        fi
    fi
done

echo -e "\nAll tests successful! ;-)"
