#!/usr/bin/env bash
set -euo pipefail

export BURL_ROOT="$(dirname `realpath $0`)"

RUN_TEST_FILE() {
    (
        set -o pipefail
        set -eux
        . ${BURL_ROOT}/common.sh
        . "$@"
        echo "--- $1 OK"
    )
}

for f in "$@"; do
    if [[ -d $f ]]; then
        for ff in $f/test-*.sh; do
            RUN_TEST_FILE "${ff}"
        done
    elif [[ -f $f ]]; then
        RUN_TEST_FILE "$f"
    fi
done

if [[ $# > 0 ]]; then
    echo -e "\nAll tests successful! ;-)"
fi
